using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SplashKitSDK;

namespace OOP_custom_project
{
    public class Define
    {
        public List<MineralType> minerals;
        public List<MineralZone> mineralZones;
        public Dictionary<(string, string), WeaponMapping> weaponMappings;
        public Define()
        {
            minerals =
            [
                new ("Iron", "A common metal used for crafting weapons and tools.", 5, 100, Color.Gray),
                new ("Gold", "A precious metal used for crafting luxury items.", 3, 50, Color.Gold),
                new ("Silver", "A precious metal used for crafting jewelry and decorative items.", 4, 70, Color.Silver),
                new ("Copper", "A versatile metal used for crafting various items.", 3, 80, Color.DarkOrange),
                new ("Obsidian", "A volcanic glass used for crafting sharp weapons.", 8, 30, Color.Black),
                new ("Mythril", "A rare and lightweight metal used for crafting superior weapons.", 7, 20, Color.Azure),
                new ("Adamantium", "An incredibly hard metal used for crafting indestructible weapons.", 10, 10, Color.DarkGray),
                new ("Platinum", "A precious metal used for crafting high-end items.", 4, 60, Color.Gainsboro),
                new ("Titanium", "A strong and lightweight metal used for advanced crafting.", 6, 40, Color.LightGray),
                new ("Uranium", "A radioactive metal used for crafting powerful items.", 9, 15, Color.DarkGreen),
                new ("Quartz", "A crystal used for crafting magical items.", 4, 90, Color.White),
                new ("Ruby", "A precious gem used for crafting enchanting items.", 5, 25, Color.Red),
                new ("Sapphire", "A precious gem used for crafting enchanting items.", 5, 25, Color.Blue),
                new ("Emerald", "A precious gem used for crafting enchanting items.", 5, 25, Color.Green),
                new ("Diamond", "A precious gem used for crafting the hardest items.", 10, 20, Color.WhiteSmoke),
                new ("Amethyst", "A precious gem used for crafting magical items.", 4, 30, Color.Purple),
                new ("Lapis", "A blue gem used for crafting decorative items.", 3, 40, Color.BlueViolet),
                new ("Onyx", "A dark gem used for crafting powerful items.", 6, 35, Color.Black),
                new ("Topaz", "A precious gem used for crafting enchanting items.", 5, 25, Color.Yellow),
                new ("Opal", "A precious gem used for crafting mystical items.", 4, 20, Color.Azure),
                new ("Garnet", "A precious gem used for crafting powerful items.", 5, 25, Color.Crimson),
                new ("Zircon", "A precious gem used for crafting durable items.", 7, 20, Color.CadetBlue),
                new ("Dragonite", "A mythical mineral used for crafting legendary items.", 9, 10, Color.Firebrick),
                new ("Etherium", "A magical mineral used for crafting otherworldly items.", 8, 15, Color.MediumPurple),
                new ("Starmetal", "A rare metal used for crafting cosmic items.", 9, 10, Color.MidnightBlue),
                new ("Moonstone", "A mystical gem used for crafting ethereal items.", 4, 20, Color.LightSteelBlue),
                new ("Sunstone", "A radiant gem used for crafting luminous items.", 5, 20, Color.Orange),
                new ("Bloodstone", "A powerful gem used for crafting warrior items.", 6, 20, Color.DarkRed),
                new ("Shadow", "A dark metal used for crafting stealthy items.", 7, 15, Color.DimGray),
                new ("Crystal Shard", "A sharp crystal used for crafting magical weapons.", 6, 30, Color.Cornsilk),
                new ("Pyrite", "A common mineral known as 'fool's gold'.", 5, 50, Color.Goldenrod),
                new ("Bismuth", "A brittle metal used in alloying.", 4, 40, Color.MediumOrchid),
                new ("Cobalt", "A metal used for creating alloys and special materials.", 6, 60, Color.MediumBlue),
                new ("Nickel", "A hard, silvery-white metal used in alloys.", 5, 70, Color.LightSlateGray),
                new ("Chromium", "A hard, lustrous metal used for plating.", 7, 80, Color.Gray),
                new ("Tungsten", "A very hard metal used for making tools.", 9, 25, Color.Silver),
                new ("Manganese", "A brittle metal used in steel production.", 6, 90, Color.BurlyWood),
                new ("Zirconium", "A metal used in high-temperature applications.", 8, 35, Color.SlateBlue),
                new ("Thorium", "A radioactive metal used in nuclear applications.", 8, 20, Color.DarkSeaGreen),
                new ("Bauxite", "A primary source of aluminum.", 4, 100, Color.DarkOrange),
                new ("Halite", "Rock salt used in various applications.", 2, 200, Color.Azure),
                new ("Graphite", "A form of carbon used in pencils and as a lubricant.", 1, 150, Color.DimGray),
                new ("Sulfur", "A yellow mineral used in chemicals and gunpowder.", 3, 180, Color.Yellow),
                new ("Phosphorite", "A mineral used in fertilizers.", 3, 200, Color.LightGoldenrodYellow),
                new ("Barite", "A mineral used in drilling fluids.", 4, 100, Color.GhostWhite),
                new ("Gypsum", "A soft mineral used in plaster and drywall.", 2, 200, Color.FloralWhite),
                new ("Fluorite", "A colorful mineral used in flux and optics.", 4, 90, Color.Cyan),
                new ("Calcite", "A mineral used in cement and lime.", 3, 150, Color.Cornsilk),
                new ("Kaolinite", "A clay mineral used in ceramics.", 2, 200, Color.Beige),
                new ("Tourmaline", "A colorful gemstone used in jewelry.", 5, 50, Color.AliceBlue),
                new ("Sodalite", "A blue mineral used in ornamental carvings.", 5, 80, Color.RoyalBlue),
                new ("Rhodochrosite", "A red to pink mineral used in jewelry.", 4, 60, Color.LightPink),
                new ("Malachite", "A green mineral used in sculptures and jewelry.", 3, 70, Color.GreenYellow),
                new ("Azurite", "A blue mineral used in pigments.", 4, 60, Color.DarkTurquoise),
                new ("Smithsonite", "A zinc carbonate mineral used in metallurgy.", 4, 70, Color.PaleGreen),
                new ("Cassiterite", "A tin oxide mineral used as a primary source of tin.", 6, 60, Color.PaleGoldenrod),
                new ("Ilmenite", "A titanium-iron oxide mineral used in titanium production.", 5, 80, Color.LightSlateGray),
                new ("Rutile", "A titanium oxide mineral used in welding and pigments.", 6, 70, Color.Tomato),
                new ("Peridot", "A green gemstone used in jewelry.", 6, 40, Color.OliveDrab),
                new ("Spinel", "A hard gemstone used in jewelry.", 7, 30, Color.Indigo),
                new ("Andalusite", "A mineral used in high-temperature ceramics.", 6, 50, Color.RosyBrown),
                new ("Kyanite", "A blue silicate mineral used in refractory materials.", 5, 70, Color.SteelBlue),
                new ("Sillimanite", "A silicate mineral used in ceramics and glass.", 6, 60, Color.SkyBlue),
                new ("Apatite", "A phosphate mineral used in fertilizer.", 5, 100, Color.Aquamarine),
                new ("Beryl", "A mineral that comes in various colors, used in jewelry.", 6, 40, Color.Aquamarine),
                new ("Turquoise", "A blue-green gemstone used in jewelry.", 5, 60, Color.Turquoise),
                new ("Heliodor", "A yellow-green variety of beryl.", 6, 30, Color.LightYellow),
                new ("Morganite", "A pink to orange-pink variety of beryl.", 6, 30, Color.MistyRose),
                new ("Goshenite", "A colorless variety of beryl.", 6, 50, Color.WhiteSmoke),
                new ("Danburite", "A mineral used in jewelry and as a collector's gem.", 7, 40, Color.LightCyan),
                new ("Rhodonite", "A pink manganese mineral used in jewelry.", 6, 50, Color.LightPink),
                new ("Serpentine", "A green mineral used in carvings and ornamental objects.", 4, 80, Color.Green),
                new ("Spodumene", "A lithium aluminum silicate mineral.", 6, 60, Color.LightSeaGreen),
                new ("Kunzite", "A pink to lilac variety of spodumene.", 6, 40, Color.Thistle),
                new ("Hiddenite", "A green variety of spodumene.", 6, 40, Color.LightGreen),
                new ("Dioptase", "A vibrant green copper silicate mineral.", 5, 30, Color.ForestGreen),
                new ("Tsavorite", "A green variety of garnet used in jewelry.", 7, 30, Color.LimeGreen),
                new ("Grossular", "A calcium-aluminum garnet mineral.", 6, 60, Color.DarkOliveGreen),
                new ("Uvarovite", "A rare green garnet mineral.", 7, 25, Color.SeaGreen),
                new ("Demantoid", "A green variety of andradite garnet.", 7, 25, Color.DarkSeaGreen),
                new ("Andradite", "A calcium-iron garnet mineral.", 7, 40, Color.DarkGreen),
                new ("Dravite", "A brown variety of tourmaline.", 7, 50, Color.SaddleBrown),
                new ("Elbaite", "A multicolored tourmaline mineral.", 7, 50, Color.MediumAquamarine),
                new ("Indicolite", "A blue variety of tourmaline.", 7, 40, Color.CornflowerBlue),
                new ("Rubellite", "A pink to red variety of tourmaline.", 7, 40, Color.PaleVioletRed),
                new ("Goshenite", "A colorless variety of beryl.", 8, 50, Color.White),
                new ("Bixbite", "A red variety of beryl, also known as red emerald.", 8, 20, Color.Firebrick),
                new ("Jeremejevite", "A rare aluminum borate mineral.", 7, 25, Color.LightSkyBlue),
                new ("Tanzanite", "A blue to violet variety of zoisite.", 6, 30, Color.BlueViolet),
                new ("Painite", "An extremely rare borate mineral.", 8, 10, Color.Brown),
                new ("Grandidierite", "A rare blue-green mineral.", 7, 15, Color.Teal),
                new ("Taaffeite", "A rare gemstone often confused with spinel.", 8, 20, Color.Orchid),
                new ("Musgravite", "A very rare gemstone related to taaffeite.", 8, 15, Color.SlateGray),
                new ("Benitoite", "A rare blue barium titanium silicate.", 6, 20, Color.LightBlue),
                new ("Alexandrite", "A color-changing variety of chrysoberyl.", 8, 20, Color.DarkSlateBlue),
                new ("Chrysoberyl", "A hard and durable gemstone.", 8, 30, Color.LightGoldenrodYellow),
                new ("Beryl", "A mineral that comes in various colors, used in jewelry.", 7, 40, Color.Aquamarine),
                new ("Spinel", "A hard gemstone used in jewelry.", 7, 30, Color.Indigo),
                new ("Zircon", "A mineral used in various industrial applications.", 8, 20, Color.Bisque),
                new ("Gabbro", "A dark, coarse-grained igneous rock.", 6, 100, Color.Black)
            ];
            mineralZones =
            [
                new (["silver_ore_zone"], "Silver Ore Zone", "A valuable zone for mining silver ore.", minerals[2], 0, 90, 70, 290, 250),
                new (["platinum_ore_zone"], "Platinum Ore Zone", "A high-end zone for mining platinum ore.", minerals[7], 0, 0, 0, 280, 70),
                new (["lapis_lazuli_zone"], "Lapis Lazuli Zone", "A decorative zone for mining lapis lazuli.", minerals[16], 0, 90, 70, 290, 230),
                new (["onyx_zone"], "Onyx Zone", "A powerful zone for mining onyx.", minerals[17], 0, 0, 70, 90, 250),
                new (["topaz_zone"], "Topaz Zone", "An enchanting zone for mining topaz.", minerals[18], 0, 0, 250, 150, 370),
                new (["copper_ore_zone"], "Copper Ore Zone", "A versatile zone for mining copper ore.", minerals[3], 0, 0, 370, 70, 500),
                new (["obsidian_zone"], "Obsidian Zone", "A dangerous zone for mining obsidian.", minerals[4], 0, 70, 370, 170, 650),
                new (["obsidian_zone"], "Obsidian Zone", "A dangerous zone for mining obsidian.", minerals[4], 0, 20, 570, 150, 670),
                new (["obsidian_zone"], "Obsidian Zone", "A dangerous zone for mining obsidian.", minerals[4], 0, 170, 480, 210, 590),
                new (["sapphire_zone"], "Sapphire Zone", "An enchanting zone for mining sapphires.", minerals[12], 0, 0, 0, 0, 0),
                new (["gold_ore_zone"], "Gold Ore Zone", "A rich zone for mining gold ore.", minerals[1], 0, 0, 500, 70, 570),
                new (["gold_ore_zone"], "Gold Ore Zone", "A rich zone for mining gold ore.", minerals[1], 0, 0, 570, 20, 810),
                new (["gold_ore_zone"], "Gold Ore Zone", "A rich zone for mining gold ore.", minerals[1], 0, 20, 670, 150, 710),
                new (["emerald_zone"], "Emerald Zone", "An enchanting zone for mining emeralds.", minerals[13], 0, 280, 0, 530, 100),
                new (["dragonite_zone"], "Dragonite Zone", "A legendary zone for mining dragonite.", minerals[22], 0, 530, 0, 590, 100),
                new (["dragonite_zone"], "Dragonite Zone", "A legendary zone for mining dragonite.", minerals[22], 50, 590, 50, 650, 130),
                new (["uranium_ore_zone"], "Uranium Ore Zone", "A powerful zone for mining uranium ore.", minerals[9], 0, 590, 0, 740, 50),
                new (["uranium_ore_zone"], "Uranium Ore Zone", "A powerful zone for mining uranium ore.", minerals[9], 0, 650, 50, 710, 100),
                new (["bloodstone_zone"], "Bloodstone Zone", "A warrior zone for mining bloodstone.", minerals[27], 0, 740, 0, 800, 50),
                new (["bloodstone_zone"], "Bloodstone Zone", "A warrior zone for mining bloodstone.", minerals[27], 0, 710, 50, 830, 100),
                new (["bloodstone_zone"], "Bloodstone Zone", "A warrior zone for mining bloodstone.", minerals[27], 0, 700, 100, 890, 210),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 800, 0, 830, 50),
                new (["titanium_ore_zone"], "Titanium Ore Zone", "An advanced zone for mining titanium ore.", minerals[8], 0, 830, 0, 960, 100),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 960, 0, 1080, 100),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 890, 100, 990, 200),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 650, 100, 700, 210),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 590, 130, 650, 210),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 590, 210, 880, 240),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 590, 210, 700, 300),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 450, 320, 610, 340),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 550, 250, 610, 320),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 860, 240, 880, 360),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 880, 290, 930, 360),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 770, 360, 870, 400),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 780, 440, 820, 540),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 720, 490, 820, 620),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 450, 340, 500, 420),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 450, 530, 500, 650),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 500, 630, 680, 650),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 610, 590, 720, 620),
                new (["iron_ore_zone"], "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 610, 620, 680, 630),
                new (["adamantium_ore_zone"], "Adamantium Ore Zone", "An indestructible zone for mining adamantium ore.", minerals[6], 0, 990, 100, 1080, 290),
                new (["adamantium_ore_zone"], "Adamantium Ore Zone", "An indestructible zone for mining adamantium ore.", minerals[6], 0, 880, 200, 990, 290),
                new (["opal_zone"], "Opal Zone", "A mystical zone for mining opals.", minerals[19], 0, 290, 100, 450, 250),
                new (["pyrite_zone"], "Pyrite Zone", "A common zone for mining pyrite.", minerals[0], 0, 450, 100, 590, 250),
                new (["pyrite_zone"], "Pyrite Zone", "A common zone for mining pyrite.", minerals[0], 0, 450, 250, 550, 320),
                new (["etherium_zone"], "Etherium Zone", "A magical zone for mining etherium.", minerals[23], 0, 150, 250, 280, 370),
                new (["crystal_shard_zone"], "Crystal Shard Zone", "A magical zone for mining crystal shards.", minerals[29], 0, 170, 370, 340, 440),
                new (["crystal_shard_zone"], "Crystal Shard Zone", "A magical zone for mining crystal shards.", minerals[29], 0, 170, 440, 210, 480),
                new (["indium_zone"], "Indium Zone", "A rare zone for mining indium.", minerals[36], 0, 280, 250, 450, 370),
                new (["indium_zone"], "Indium Zone", "A rare zone for mining indium.", minerals[36], 0, 340, 370, 410, 400),
                new (["garnet_zone"], "Garnet Zone", "A powerful zone for mining garnets.", minerals[0], 0, 210, 440, 450, 590),
                new (["garnet_zone"], "Garnet Zone", "A powerful zone for mining garnets.", minerals[0], 0, 340, 400, 450, 440),
                new (["garnet_zone"], "Garnet Zone", "A powerful zone for mining garnets.", minerals[0], 0, 410, 370, 450, 400),
                new (["uranium_zone"], "Uranium Zone", "A radioactive zone for mining uranium.", minerals[65], 0, 700, 240, 860, 360),
                new (["sunstone_zone"], "Sunstone Zone", "A luminous zone for mining sunstone.", minerals[26], 0, 610, 300, 700, 360),
                new (["nickel_zone"], "Nickel Zone", "An alloy zone for mining nickel.", minerals[33], 0, 500, 340, 610, 630),
                new (["nickel_zone"], "Nickel Zone", "An alloy zone for mining nickel.", minerals[33], 0, 450, 420, 500, 530),
                new (["nickel_zone"], "Nickel Zone", "An alloy zone for mining nickel.", minerals[33], 0, 610, 360, 720, 590),
                new (["nickel_zone"], "Nickel Zone", "An alloy zone for mining nickel.", minerals[33], 0, 710, 360, 780, 490),
                new (["mythril_ore_zone"], "Mythril Ore Zone", "A rare zone for mining mythril ore.", minerals[5], 0, 930, 290, 1080, 360),
                new (["moonstone_zone"], "Moonstone Zone", "An ethereal zone for mining moonstone.", minerals[25], 0, 870, 360, 1080, 460),
                new (["cobalt_zone"], "Cobalt Zone", "A special zone for mining cobalt.", minerals[32], 0, 780, 400, 870, 440),
                new (["cobalt_zone"], "Cobalt Zone", "A special zone for mining cobalt.", minerals[32], 0, 820, 440, 870, 500),
                new (["cobalt_zone"], "Cobalt Zone", "A special zone for mining cobalt.", minerals[32], 0, 870, 460, 1080, 520),
                new (["cobalt_zone"], "Cobalt Zone", "A special zone for mining cobalt.", minerals[32], 0, 1000, 520, 1080, 580),
                new (["starmetal_zone"], "Starmetal Zone", "A cosmic zone for mining starmetal.", minerals[24], 50, 820, 500, 870, 580),
                new (["starmetal_zone"], "Starmetal Zone", "A cosmic zone for mining starmetal.", minerals[24], 50, 870, 520, 1000, 580),
                new (["shadow_ore_zone"], "Shadow Ore Zone", "A stealthy zone for mining shadow ore.", minerals[28], 0, 820, 580, 970, 700),
                new (["diamond_zone"], "Diamond Zone", "A hard zone for mining diamonds.", minerals[14], 0, 20, 710, 320, 810),
                new (["ruby_zone"], "Ruby Zone", "An enchanting zone for mining rubies.", minerals[11], 0, 970, 580, 1080, 700),
                new (["ruby_zone"], "Ruby Zone", "An enchanting zone for mining rubies.", minerals[11], 0, 890, 700, 1080, 810),
                new (["amethyst_zone"], "Amethyst Zone", "A magical zone for mining amethysts.", minerals[15], 0, 170, 590, 450, 650),
                new (["zircon_zone"], "Zircon Zone", "A durable zone for mining zircons.", minerals[21], 0, 150, 650, 380, 710),
                new (["seaborgium_zone"], "Seaborgium Zone", "A radioactive zone for mining seaborgium.", minerals[79], 0, 320, 710, 810, 810),
                new (["bismuth_zone"], "Bismuth Zone", "An alloy zone for mining bismuth.", minerals[31], 0, 810, 700, 890, 810),
                new (["yttrium_zone"], "Yttrium Zone", "A phosphorescent zone for mining yttrium.", minerals[45], 0, 680, 620, 820, 710),
                new (["lutetium_zone"], "Lutetium Zone", "A heavy zone for mining lutetium.", minerals[60], 0, 380, 650, 680, 710),
            ];
            weaponMappings = new Dictionary<(string, string), WeaponMapping>
            {
                { ("Adamantium", "Bloodstone"), new WeaponMapping { WeaponName = "Adamantite Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Adamantite_Sword.png" } },
                { ("Silver", "Lapis"), new WeaponMapping { WeaponName = "Arkhalis", ImageFile = @"D:\OOP-custom-project\downloaded_images\Arkhalis.png" } },
                { ("Manganese", "Etherium"), new WeaponMapping { WeaponName = "Ash Wood Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Ash_Wood_Sword.png" } },
                { ("Iron", "Bloodstone"), new WeaponMapping { WeaponName = "Bat Bat", ImageFile = @"D:\OOP-custom-project\downloaded_images\Bat_Bat.png" } },
                { ("Opal", "Zircon"), new WeaponMapping { WeaponName = "Beam Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Beam_Sword.png" } },
                { ("Gold", "Obsidian"), new WeaponMapping { WeaponName = "Bee Keeper", ImageFile = @"D:\OOP-custom-project\downloaded_images\Bee_Keeper.png" } },
                { ("Onyx", "Cobalt"), new WeaponMapping { WeaponName = "Bladed Glove", ImageFile = @"D:\OOP-custom-project\downloaded_images\Bladed_Glove.png" } },
                { ("Ruby", "Garnet"), new WeaponMapping { WeaponName = "Bladetongue", ImageFile = @"D:\OOP-custom-project\downloaded_images\Bladetongue.png" } },
                { ("Emerald", "Adamantium"), new WeaponMapping { WeaponName = "Blade of Grass", ImageFile = @"D:\OOP-custom-project\downloaded_images\Blade_of_Grass.png" } },
                { ("Bloodstone", "Dragonite"), new WeaponMapping { WeaponName = "Blood Butcherer", ImageFile = @"D:\OOP-custom-project\downloaded_images\Blood_Butcherer.png" } },
                { ("Silver", "Uranium"), new WeaponMapping { WeaponName = "Blue Phaseblade", ImageFile = @"D:\OOP-custom-project\downloaded_images\Blue_Phaseblade.png" } },
                { ("Silver", "Bloodstone"), new WeaponMapping { WeaponName = "Bone Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Bone_Sword.png" } },
                { ("Silver", "Iron"), new WeaponMapping { WeaponName = "Boreal Wood Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Boreal_Wood_Sword.png" } },
                { ("Silver", "Titanium"), new WeaponMapping { WeaponName = "Brand of the Inferno", ImageFile = @"D:\OOP-custom-project\downloaded_images\Brand_of_the_Inferno.png" } },
                { ("Silver", "Adamantium"), new WeaponMapping { WeaponName = "Breaker Blade", ImageFile = @"D:\OOP-custom-project\downloaded_images\Breaker_Blade.png" } },
                { ("Silver", "Opal"), new WeaponMapping { WeaponName = "Breathing Reed", ImageFile = @"D:\OOP-custom-project\downloaded_images\Breathing_Reed.png" } },
                { ("Silver", "Pyrite"), new WeaponMapping { WeaponName = "Cactus Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Cactus_Sword.png" } },
                { ("Silver", "Etherium"), new WeaponMapping { WeaponName = "Candy Cane Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Candy_Cane_Sword.png" } },
                { ("Silver", "Crystal"), new WeaponMapping { WeaponName = "Chlorophyte Claymore", ImageFile = @"D:\OOP-custom-project\downloaded_images\Chlorophyte_Claymore.png" } },
                { ("Silver", "Indium"), new WeaponMapping { WeaponName = "Chlorophyte Saber", ImageFile = @"D:\OOP-custom-project\downloaded_images\Chlorophyte_Saber.png" } },
                { ("Silver", "Garnet"), new WeaponMapping { WeaponName = "Christmas Tree Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Christmas_Tree_Sword.png" } },
                { ("Silver", "Sunstone"), new WeaponMapping { WeaponName = "Classy Cane", ImageFile = @"D:\OOP-custom-project\downloaded_images\Classy_Cane.png" } },
                { ("Silver", "Nickel"), new WeaponMapping { WeaponName = "Cobalt Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Cobalt_Sword.png" } },
                { ("Silver", "Mythril"), new WeaponMapping { WeaponName = "Copper Broadsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Copper_Broadsword.png" } },
                { ("Silver", "Moonstone"), new WeaponMapping { WeaponName = "Copper Shortsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Copper_Shortsword.png" } },
                { ("Silver", "Cobalt"), new WeaponMapping { WeaponName = "Cutlass", ImageFile = @"D:\OOP-custom-project\downloaded_images\Cutlass.png" } },
                { ("Silver", "Starmetal"), new WeaponMapping { WeaponName = "Daybreak", ImageFile = @"D:\OOP-custom-project\downloaded_images\Daybreak.png" } },
                { ("Silver", "Shadow"), new WeaponMapping { WeaponName = "Death Sickle", ImageFile = @"D:\OOP-custom-project\downloaded_images\Death_Sickle.png" } },
                { ("Silver", "Diamond"), new WeaponMapping { WeaponName = "Ebonwood Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Ebonwood_Sword.png" } },
                { ("Silver", "Ruby"), new WeaponMapping { WeaponName = "Enchanted Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Enchanted_Sword_(item).png" } },
                { ("Silver", "Amethyst"), new WeaponMapping { WeaponName = "Excalibur", ImageFile = @"D:\OOP-custom-project\downloaded_images\Excalibur.png" } },
                { ("Silver", "Zircon"), new WeaponMapping { WeaponName = "Exotic Scimitar", ImageFile = @"D:\OOP-custom-project\downloaded_images\Exotic_Scimitar.png" } },
                { ("Silver", "Seaborgium"), new WeaponMapping { WeaponName = "Falcon Blade", ImageFile = @"D:\OOP-custom-project\downloaded_images\Falcon_Blade.png" } },
                { ("Silver", "Bismuth"), new WeaponMapping { WeaponName = "Fetid Baghnakhs", ImageFile = @"D:\OOP-custom-project\downloaded_images\Fetid_Baghnakhs.png" } },
                { ("Silver", "Yttrium"), new WeaponMapping { WeaponName = "Fiery Greatsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Fiery_Greatsword.png" } },
                { ("Sunstone", "Pyrite"), new WeaponMapping { WeaponName = "Flying Dragon", ImageFile = @"D:\OOP-custom-project\downloaded_images\Flying_Dragon.png" } },
                { ("Platinum", "Lapis"), new WeaponMapping { WeaponName = "Frostbrand", ImageFile = @"D:\OOP-custom-project\downloaded_images\Frostbrand.png" } },
                { ("Platinum", "Onyx"), new WeaponMapping { WeaponName = "Gladius", ImageFile = @"D:\OOP-custom-project\downloaded_images\Gladius.png" } },
                { ("Platinum", "Topaz"), new WeaponMapping { WeaponName = "Gold Broadsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Gold_Broadsword.png" } },
                { ("Platinum", "Copper"), new WeaponMapping { WeaponName = "Gold Shortsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Gold_Shortsword.png" } },
                { ("Platinum", "Obsidian"), new WeaponMapping { WeaponName = "Hallowed Jousting Lance", ImageFile = @"D:\OOP-custom-project\downloaded_images\Hallowed_Jousting_Lance.png" } },
                { ("Platinum", "Sapphire"), new WeaponMapping { WeaponName = "Ham Bat", ImageFile = @"D:\OOP-custom-project\downloaded_images\Ham_Bat.png" } },
                { ("Platinum", "Gold"), new WeaponMapping { WeaponName = "Ice Blade", ImageFile = @"D:\OOP-custom-project\downloaded_images\Ice_Blade.png" } },
                { ("Platinum", "Emerald"), new WeaponMapping { WeaponName = "Ice Sickle", ImageFile = @"D:\OOP-custom-project\downloaded_images\Ice_Sickle.png" } },
                { ("Platinum", "Dragonite"), new WeaponMapping { WeaponName = "Influx Waver", ImageFile = @"D:\OOP-custom-project\downloaded_images\Influx_Waver.png" } },
                { ("Platinum", "Uranium"), new WeaponMapping { WeaponName = "Iron Broadsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Iron_Broadsword.png" } },
                { ("Platinum", "Bloodstone"), new WeaponMapping { WeaponName = "Iron Shortsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Iron_Shortsword.png" } },
                { ("Platinum", "Titanium"), new WeaponMapping { WeaponName = "Jousting Lance", ImageFile = @"D:\OOP-custom-project\downloaded_images\Jousting_Lance.png" } },
                { ("Platinum", "Adamantium"), new WeaponMapping { WeaponName = "Katana", ImageFile = @"D:\OOP-custom-project\downloaded_images\Katana.png" } },
                { ("Platinum", "Opal"), new WeaponMapping { WeaponName = "Keybrand", ImageFile = @"D:\OOP-custom-project\downloaded_images\Keybrand.png" } },
                { ("Platinum", "Pyrite"), new WeaponMapping { WeaponName = "Lead Broadsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Lead_Broadsword.png" } },
                { ("Platinum", "Etherium"), new WeaponMapping { WeaponName = "Lead Shortsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Lead_Shortsword.png" } },
                { ("Platinum", "Crystal"), new WeaponMapping { WeaponName = "Light's Bane", ImageFile = @"D:\OOP-custom-project\downloaded_images\Light%27s_Bane.png" } },
                { ("Platinum", "Indium"), new WeaponMapping { WeaponName = "Mandible Blade", ImageFile = @"D:\OOP-custom-project\downloaded_images\Mandible_Blade.png" } },
                { ("Zircon", "Diamond"), new WeaponMapping { WeaponName = "Meowmere", ImageFile = @"D:\OOP-custom-project\downloaded_images\Meowmere.png" } },
                { ("Crystal", "Seaborgium"), new WeaponMapping { WeaponName = "Muramasa", ImageFile = @"D:\OOP-custom-project\downloaded_images\Muramasa.png" } },
                { ("Platinum", "Nickel"), new WeaponMapping { WeaponName = "Mythril Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Mythril_Sword.png" } },
                { ("Platinum", "Mythril"), new WeaponMapping { WeaponName = "Night's Edge", ImageFile = @"D:\OOP-custom-project\downloaded_images\Night%27s_Edge.png" } },
                { ("Platinum", "Moonstone"), new WeaponMapping { WeaponName = "Orichalcum Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Orichalcum_Sword.png" } },
                { ("Platinum", "Cobalt"), new WeaponMapping { WeaponName = "Palladium Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Palladium_Sword.png" } },
                { ("Platinum", "Starmetal"), new WeaponMapping { WeaponName = "Palm Wood Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Palm_Wood_Sword.png" } },
                { ("Platinum", "Shadow"), new WeaponMapping { WeaponName = "Pearlwood Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Pearlwood_Sword.png" } },
                { ("Platinum", "Diamond"), new WeaponMapping { WeaponName = "Platinum Broadsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Platinum_Broadsword.png" } },
                { ("Platinum", "Ruby"), new WeaponMapping { WeaponName = "Platinum Shortsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Platinum_Shortsword.png" } },
                { ("Platinum", "Amethyst"), new WeaponMapping { WeaponName = "Psycho Knife", ImageFile = @"D:\OOP-custom-project\downloaded_images\Psycho_Knife.png" } },
                { ("Platinum", "Zircon"), new WeaponMapping { WeaponName = "Purple Clubberfish", ImageFile = @"D:\OOP-custom-project\downloaded_images\Purple_Clubberfish.png" } },
                { ("Platinum", "Seaborgium"), new WeaponMapping { WeaponName = "Rich Mahogany Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Rich_Mahogany_Sword.png" } },
                { ("Platinum", "Bismuth"), new WeaponMapping { WeaponName = "Scourge of the Corruptor", ImageFile = @"D:\OOP-custom-project\downloaded_images\Scourge_of_the_Corruptor.png" } },
                { ("Platinum", "Yttrium"), new WeaponMapping { WeaponName = "Seedler", ImageFile = @"D:\OOP-custom-project\downloaded_images\Seedler.png" } },
                { ("Platinum", "Lutetium"), new WeaponMapping { WeaponName = "Shadewood Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Shadewood_Sword.png" } },
                { ("Lapis", "Onyx"), new WeaponMapping { WeaponName = "Shadowflame Knife", ImageFile = @"D:\OOP-custom-project\downloaded_images\Shadowflame_Knife.png" } },
                { ("Lapis", "Topaz"), new WeaponMapping { WeaponName = "Shadow Jousting Lance", ImageFile = @"D:\OOP-custom-project\downloaded_images\Shadow_Jousting_Lance.png" } },
                { ("Lapis", "Copper"), new WeaponMapping { WeaponName = "Silver Broadsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Silver_Broadsword.png" } },
                { ("Lapis", "Obsidian"), new WeaponMapping { WeaponName = "Silver Shortsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Silver_Shortsword.png" } },
                { ("Lapis", "Sapphire"), new WeaponMapping { WeaponName = "Sky Dragon's Fury", ImageFile = @"D:\OOP-custom-project\downloaded_images\Sky_Dragon%27s_Fury.png" } },
                { ("Lapis", "Gold"), new WeaponMapping { WeaponName = "Slap Hand", ImageFile = @"D:\OOP-custom-project\downloaded_images\Slap_Hand.png" } },
                { ("Lapis", "Emerald"), new WeaponMapping { WeaponName = "Sleepy Octopod", ImageFile = @"D:\OOP-custom-project\downloaded_images\Sleepy_Octopod.png" } },
                { ("Lapis", "Dragonite"), new WeaponMapping { WeaponName = "Starfury", ImageFile = @"D:\OOP-custom-project\downloaded_images\Starfury.png" } },
                { ("Lapis", "Uranium"), new WeaponMapping { WeaponName = "Starlight", ImageFile = @"D:\OOP-custom-project\downloaded_images\Starlight.png" } },
                { ("Lapis", "Bloodstone"), new WeaponMapping { WeaponName = "Star Wrath", ImageFile = @"D:\OOP-custom-project\downloaded_images\Star_Wrath.png" } },
                { ("Lapis", "Iron"), new WeaponMapping { WeaponName = "Stylish Scissors", ImageFile = @"D:\OOP-custom-project\downloaded_images\Stylish_Scissors.png" } },
                { ("Lapis", "Titanium"), new WeaponMapping { WeaponName = "sword_0", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_0.png" } },
                { ("Lapis", "Adamantium"), new WeaponMapping { WeaponName = "sword_1", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_1.png" } },
                { ("Lapis", "Opal"), new WeaponMapping { WeaponName = "sword_2", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_2.png" } },
                { ("Lapis", "Pyrite"), new WeaponMapping { WeaponName = "sword_3", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_3.png" } },
                { ("Lapis", "Etherium"), new WeaponMapping { WeaponName = "sword_4", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_4.png" } },
                { ("Lapis", "Crystal"), new WeaponMapping { WeaponName = "sword_5", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_5.png" } },
                { ("Lapis", "Indium"), new WeaponMapping { WeaponName = "sword_6", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_6.png" } },
                { ("Lapis", "Garnet"), new WeaponMapping { WeaponName = "sword_7", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_7.png" } },
                { ("Lapis", "Sunstone"), new WeaponMapping { WeaponName = "sword_8", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_8.png" } },
                { ("Lapis", "Nickel"), new WeaponMapping { WeaponName = "sword_9", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_9.png" } },
                { ("Lapis", "Mythril"), new WeaponMapping { WeaponName = "sword_10", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_10.png" } },
                { ("Lapis", "Moonstone"), new WeaponMapping { WeaponName = "sword_11", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_11.png" } },
                { ("Lapis", "Cobalt"), new WeaponMapping { WeaponName = "sword_12", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_12.png" } },
                { ("Lapis", "Starmetal"), new WeaponMapping { WeaponName = "sword_13", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_13.png" } },
                { ("Lapis", "Shadow"), new WeaponMapping { WeaponName = "sword_14", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_14.png" } },
                { ("Lapis", "Diamond"), new WeaponMapping { WeaponName = "sword_15", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_15.png" } },
                { ("Lapis", "Ruby"), new WeaponMapping { WeaponName = "sword_16", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_16.png" } },
                { ("Lapis", "Amethyst"), new WeaponMapping { WeaponName = "sword_17", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_17.png" } },
                { ("Lapis", "Zircon"), new WeaponMapping { WeaponName = "sword_18", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_18.png" } },
                { ("Lapis", "Seaborgium"), new WeaponMapping { WeaponName = "sword_19", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_19.png" } },
                { ("Lapis", "Bismuth"), new WeaponMapping { WeaponName = "sword_20", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_20.png" } },
                { ("Lapis", "Yttrium"), new WeaponMapping { WeaponName = "sword_21", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_21.png" } },
                { ("Lapis", "Lutetium"), new WeaponMapping { WeaponName = "sword_24", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_24.png" } },
                { ("Onyx", "Topaz"), new WeaponMapping { WeaponName = "sword_25", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_25.png" } },
                { ("Onyx", "Copper"), new WeaponMapping { WeaponName = "sword_26", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_26.png" } },
                { ("Onyx", "Obsidian"), new WeaponMapping { WeaponName = "sword_27", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_27.png" } },
                { ("Onyx", "Sapphire"), new WeaponMapping { WeaponName = "sword_28", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_28.png" } },
                { ("Onyx", "Gold"), new WeaponMapping { WeaponName = "sword_29", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_29.png" } },
                { ("Onyx", "Emerald"), new WeaponMapping { WeaponName = "sword_3", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_3.png" } },
                { ("Onyx", "Dragonite"), new WeaponMapping { WeaponName = "sword_30", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_30.png" } },
                { ("Onyx", "Uranium"), new WeaponMapping { WeaponName = "sword_31", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_31.png" } },
                { ("Onyx", "Bloodstone"), new WeaponMapping { WeaponName = "sword_32", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_32.png" } },
                { ("Onyx", "Iron"), new WeaponMapping { WeaponName = "sword_33", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_33.png" } },
                { ("Onyx", "Titanium"), new WeaponMapping { WeaponName = "sword_34", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_34.png" } },
                { ("Onyx", "Adamantium"), new WeaponMapping { WeaponName = "sword_35", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_35.png" } },
                { ("Onyx", "Opal"), new WeaponMapping { WeaponName = "sword_36", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_36.png" } },
                { ("Onyx", "Pyrite"), new WeaponMapping { WeaponName = "sword_37", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_37.png" } },
                { ("Onyx", "Etherium"), new WeaponMapping { WeaponName = "sword_38", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_38.png" } },
                { ("Onyx", "Crystal"), new WeaponMapping { WeaponName = "sword_39", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_39.png" } },
                { ("Onyx", "Indium"), new WeaponMapping { WeaponName = "sword_4", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_4.png" } },
                { ("Onyx", "Garnet"), new WeaponMapping { WeaponName = "sword_40", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_40.png" } },
                { ("Onyx", "Sunstone"), new WeaponMapping { WeaponName = "sword_41", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_41.png" } },
                { ("Onyx", "Nickel"), new WeaponMapping { WeaponName = "sword_42", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_42.png" } },
                { ("Onyx", "Mythril"), new WeaponMapping { WeaponName = "sword_43", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_43.png" } },
                { ("Onyx", "Moonstone"), new WeaponMapping { WeaponName = "sword_44", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_44.png" } },
                { ("Opal", "Cobalt"), new WeaponMapping { WeaponName = "sword_45", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_45.png" } },
                { ("Onyx", "Starmetal"), new WeaponMapping { WeaponName = "sword_46", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_46.png" } },
                { ("Nickel", "Iron"), new WeaponMapping { WeaponName = "sword_47", ImageFile = @"D:\OOP-custom-project\downloaded_images\sword_47.png" } },
                { ("Onyx", "Diamond"), new WeaponMapping { WeaponName = "Tentacle Spike", ImageFile = @"D:\OOP-custom-project\downloaded_images\Tentacle_Spike.png" } },
                { ("Onyx", "Ruby"), new WeaponMapping { WeaponName = "Terra Blade", ImageFile = @"D:\OOP-custom-project\downloaded_images\Terra_Blade.png" } },
                { ("Onyx", "Amethyst"), new WeaponMapping { WeaponName = "The Horseman's Blade", ImageFile = @"D:\OOP-custom-project\downloaded_images\The_Horseman%27s_Blade.png" } },
                { ("Onyx", "Zircon"), new WeaponMapping { WeaponName = "Tin Broadsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Tin_Broadsword.png" } },
                { ("Onyx", "Seaborgium"), new WeaponMapping { WeaponName = "Tin Shortsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Tin_Shortsword.png" } },
                { ("Opal", "Titanium"), new WeaponMapping { WeaponName = "Titanium Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Titanium_Sword.png" } },
                { ("Onyx", "Yttrium"), new WeaponMapping { WeaponName = "Tungsten Broadsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Tungsten_Broadsword.png" } },
                { ("Onyx", "Lutetium"), new WeaponMapping { WeaponName = "Tungsten Shortsword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Tungsten_Shortsword.png" } },
                { ("Topaz", "Copper"), new WeaponMapping { WeaponName = "Umbrella", ImageFile = @"D:\OOP-custom-project\downloaded_images\Umbrella.png" } },
                { ("Topaz", "Obsidian"), new WeaponMapping { WeaponName = "Wooden Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Wooden_Sword.png" } },
                { ("Etherium", "Starmetal"), new WeaponMapping { WeaponName = "Zenith Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Zenith.png" } },
                { ("Etherium", "Indium"), new WeaponMapping { WeaponName = "Tizona Sword", ImageFile = @"D:\OOP-custom-project\downloaded_images\Tizona.png" } },
                { ("Topaz", "Uranium"), new WeaponMapping { WeaponName = "Zombie Arm", ImageFile = @"D:\OOP-custom-project\downloaded_images\Zombie_Arm.png" } }
            };
        }
        public MineralType AssignMineral(double x, double y)
        {
            foreach(var zone  in mineralZones)
            {
                if(IsInZone(x, y, zone))
                    return zone._mineral;
            }
            return null;
        }
        private static bool IsInZone(double x, double y, MineralZone zone)
        {
            return (x > zone.startX && y > zone.startY && x < zone.endX && y < zone.endY);
        }
    }
}
