using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SplashKitSDK;

namespace OOP_custom_project
{
    public class DefineMineral
    {
        public List<MineralType> minerals;
        public List<MineralZone> mineralZones;
        public DefineMineral()
        {
            minerals = new List<MineralType>
            {
                new MineralType("Iron Ore", "A common metal used for crafting weapons and tools.", 5, 100, Color.Gray),
                new MineralType("Gold Ore", "A precious metal used for crafting luxury items.", 3, 50, Color.Gold),
                new MineralType("Silver Ore", "A precious metal used for crafting jewelry and decorative items.", 4, 70, Color.Silver),
                new MineralType("Copper Ore", "A versatile metal used for crafting various items.", 3, 80, Color.DarkOrange),
                new MineralType("Obsidian", "A volcanic glass used for crafting sharp weapons.", 8, 30, Color.Black),
                new MineralType("Mythril Ore", "A rare and lightweight metal used for crafting superior weapons.", 7, 20, Color.Azure),
                new MineralType("Adamantium Ore", "An incredibly hard metal used for crafting indestructible weapons.", 10, 10, Color.DarkGray),
                new MineralType("Platinum Ore", "A precious metal used for crafting high-end items.", 4, 60, Color.Gainsboro),
                new MineralType("Titanium Ore", "A strong and lightweight metal used for advanced crafting.", 6, 40, Color.LightGray),
                new MineralType("Uranium Ore", "A radioactive metal used for crafting powerful items.", 9, 15, Color.DarkGreen),
                new MineralType("Quartz", "A crystal used for crafting magical items.", 4, 90, Color.White),
                new MineralType("Ruby", "A precious gem used for crafting enchanting items.", 5, 25, Color.Red),
                new MineralType("Sapphire", "A precious gem used for crafting enchanting items.", 5, 25, Color.Blue),
                new MineralType("Emerald", "A precious gem used for crafting enchanting items.", 5, 25, Color.Green),
                new MineralType("Diamond", "A precious gem used for crafting the hardest items.", 10, 20, Color.WhiteSmoke),
                new MineralType("Amethyst", "A precious gem used for crafting magical items.", 4, 30, Color.Purple),
                new MineralType("Lapis Lazuli", "A blue gem used for crafting decorative items.", 3, 40, Color.BlueViolet),
                new MineralType("Onyx", "A dark gem used for crafting powerful items.", 6, 35, Color.Black),
                new MineralType("Topaz", "A precious gem used for crafting enchanting items.", 5, 25, Color.Yellow),
                new MineralType("Opal", "A precious gem used for crafting mystical items.", 4, 20, Color.Azure),
                new MineralType("Garnet", "A precious gem used for crafting powerful items.", 5, 25, Color.Crimson),
                new MineralType("Zircon", "A precious gem used for crafting durable items.", 7, 20, Color.CadetBlue),
                new MineralType("Dragonite", "A mythical mineral used for crafting legendary items.", 9, 10, Color.Firebrick),
                new MineralType("Etherium", "A magical mineral used for crafting otherworldly items.", 8, 15, Color.MediumPurple),
                new MineralType("Starmetal", "A rare metal used for crafting cosmic items.", 9, 10, Color.MidnightBlue),
                new MineralType("Moonstone", "A mystical gem used for crafting ethereal items.", 4, 20, Color.LightSteelBlue),
                new MineralType("Sunstone", "A radiant gem used for crafting luminous items.", 5, 20, Color.Orange),
                new MineralType("Bloodstone", "A powerful gem used for crafting warrior items.", 6, 20, Color.DarkRed),
                new MineralType("Shadow Ore", "A dark metal used for crafting stealthy items.", 7, 15, Color.DimGray),
                new MineralType("Crystal Shard", "A sharp crystal used for crafting magical weapons.", 6, 30, Color.Cornsilk),
                new MineralType("Pyrite", "A common mineral known as 'fool's gold'.", 5, 50, Color.Goldenrod),
                new MineralType("Bismuth", "A brittle metal used in alloying.", 4, 40, Color.MediumOrchid),
                new MineralType("Cobalt", "A metal used for creating alloys and special materials.", 6, 60, Color.MediumBlue),
                new MineralType("Nickel", "A hard, silvery-white metal used in alloys.", 5, 70, Color.LightSlateGray),
                new MineralType("Chromium", "A hard, lustrous metal used for plating.", 7, 80, Color.Gray),
                new MineralType("Tungsten", "A very hard metal used for making tools.", 9, 25, Color.Silver),
                new MineralType("Manganese", "A brittle metal used in steel production.", 6, 90, Color.BurlyWood),
                new MineralType("Zirconium", "A metal used in high-temperature applications.", 8, 35, Color.SlateBlue),
                new MineralType("Thorium", "A radioactive metal used in nuclear applications.", 8, 20, Color.DarkSeaGreen),
                new MineralType("Bauxite", "A primary source of aluminum.", 4, 100, Color.DarkOrange),
                new MineralType("Halite", "Rock salt used in various applications.", 2, 200, Color.Azure),
                new MineralType("Graphite", "A form of carbon used in pencils and as a lubricant.", 1, 150, Color.DimGray),
                new MineralType("Sulfur", "A yellow mineral used in chemicals and gunpowder.", 3, 180, Color.Yellow),
                new MineralType("Phosphorite", "A mineral used in fertilizers.", 3, 200, Color.LightGoldenrodYellow),
                new MineralType("Barite", "A mineral used in drilling fluids.", 4, 100, Color.GhostWhite),
                new MineralType("Gypsum", "A soft mineral used in plaster and drywall.", 2, 200, Color.FloralWhite),
                new MineralType("Fluorite", "A colorful mineral used in flux and optics.", 4, 90, Color.Cyan),
                new MineralType("Calcite", "A mineral used in cement and lime.", 3, 150, Color.Cornsilk),
                new MineralType("Kaolinite", "A clay mineral used in ceramics.", 2, 200, Color.Beige),
                new MineralType("Tourmaline", "A colorful gemstone used in jewelry.", 5, 50, Color.AliceBlue),
                new MineralType("Sodalite", "A blue mineral used in ornamental carvings.", 5, 80, Color.RoyalBlue),
                new MineralType("Rhodochrosite", "A red to pink mineral used in jewelry.", 4, 60, Color.LightPink),
                new MineralType("Malachite", "A green mineral used in sculptures and jewelry.", 3, 70, Color.GreenYellow),
                new MineralType("Azurite", "A blue mineral used in pigments.", 4, 60, Color.DarkTurquoise),
                new MineralType("Smithsonite", "A zinc carbonate mineral used in metallurgy.", 4, 70, Color.PaleGreen),
                new MineralType("Cassiterite", "A tin oxide mineral used as a primary source of tin.", 6, 60, Color.PaleGoldenrod),
                new MineralType("Ilmenite", "A titanium-iron oxide mineral used in titanium production.", 5, 80, Color.LightSlateGray),
                new MineralType("Rutile", "A titanium oxide mineral used in welding and pigments.", 6, 70, Color.Tomato),
                new MineralType("Peridot", "A green gemstone used in jewelry.", 6, 40, Color.OliveDrab),
                new MineralType("Spinel", "A hard gemstone used in jewelry.", 7, 30, Color.Indigo),
                new MineralType("Andalusite", "A mineral used in high-temperature ceramics.", 6, 50, Color.RosyBrown),
                new MineralType("Kyanite", "A blue silicate mineral used in refractory materials.", 5, 70, Color.SteelBlue),
                new MineralType("Sillimanite", "A silicate mineral used in ceramics and glass.", 6, 60, Color.SkyBlue),
                new MineralType("Apatite", "A phosphate mineral used in fertilizer.", 5, 100, Color.Aquamarine),
                new MineralType("Beryl", "A mineral that comes in various colors, used in jewelry.", 6, 40, Color.Aquamarine),
                new MineralType("Turquoise", "A blue-green gemstone used in jewelry.", 5, 60, Color.Turquoise),
                new MineralType("Heliodor", "A yellow-green variety of beryl.", 6, 30, Color.LightYellow),
                new MineralType("Morganite", "A pink to orange-pink variety of beryl.", 6, 30, Color.MistyRose),
                new MineralType("Goshenite", "A colorless variety of beryl.", 6, 50, Color.WhiteSmoke),
                new MineralType("Danburite", "A mineral used in jewelry and as a collector's gem.", 7, 40, Color.LightCyan),
                new MineralType("Rhodonite", "A pink manganese mineral used in jewelry.", 6, 50, Color.LightPink),
                new MineralType("Serpentine", "A green mineral used in carvings and ornamental objects.", 4, 80, Color.Green),
                new MineralType("Spodumene", "A lithium aluminum silicate mineral.", 6, 60, Color.LightSeaGreen),
                new MineralType("Kunzite", "A pink to lilac variety of spodumene.", 6, 40, Color.Thistle),
                new MineralType("Hiddenite", "A green variety of spodumene.", 6, 40, Color.LightGreen),
                new MineralType("Dioptase", "A vibrant green copper silicate mineral.", 5, 30, Color.ForestGreen),
                new MineralType("Tsavorite", "A green variety of garnet used in jewelry.", 7, 30, Color.LimeGreen),
                new MineralType("Grossular", "A calcium-aluminum garnet mineral.", 6, 60, Color.DarkOliveGreen),
                new MineralType("Uvarovite", "A rare green garnet mineral.", 7, 25, Color.SeaGreen),
                new MineralType("Demantoid", "A green variety of andradite garnet.", 7, 25, Color.DarkSeaGreen),
                new MineralType("Andradite", "A calcium-iron garnet mineral.", 7, 40, Color.DarkGreen),
                new MineralType("Dravite", "A brown variety of tourmaline.", 7, 50, Color.SaddleBrown),
                new MineralType("Elbaite", "A multicolored tourmaline mineral.", 7, 50, Color.MediumAquamarine),
                new MineralType("Indicolite", "A blue variety of tourmaline.", 7, 40, Color.CornflowerBlue),
                new MineralType("Rubellite", "A pink to red variety of tourmaline.", 7, 40, Color.PaleVioletRed),
                new MineralType("Goshenite", "A colorless variety of beryl.", 8, 50, Color.White),
                new MineralType("Bixbite", "A red variety of beryl, also known as red emerald.", 8, 20, Color.Firebrick),
                new MineralType("Jeremejevite", "A rare aluminum borate mineral.", 7, 25, Color.LightSkyBlue),
                new MineralType("Tanzanite", "A blue to violet variety of zoisite.", 6, 30, Color.BlueViolet),
                new MineralType("Painite", "An extremely rare borate mineral.", 8, 10, Color.Brown),
                new MineralType("Grandidierite", "A rare blue-green mineral.", 7, 15, Color.Teal),
                new MineralType("Taaffeite", "A rare gemstone often confused with spinel.", 8, 20, Color.Orchid),
                new MineralType("Musgravite", "A very rare gemstone related to taaffeite.", 8, 15, Color.SlateGray),
                new MineralType("Benitoite", "A rare blue barium titanium silicate.", 6, 20, Color.LightBlue),
                new MineralType("Alexandrite", "A color-changing variety of chrysoberyl.", 8, 20, Color.DarkSlateBlue),
                new MineralType("Chrysoberyl", "A hard and durable gemstone.", 8, 30, Color.LightGoldenrodYellow),
                new MineralType("Beryl", "A mineral that comes in various colors, used in jewelry.", 7, 40, Color.Aquamarine),
                new MineralType("Spinel", "A hard gemstone used in jewelry.", 7, 30, Color.Indigo),
                new MineralType("Zircon", "A mineral used in various industrial applications.", 8, 20, Color.Bisque),
                new MineralType("Gabbro", "A dark, coarse-grained igneous rock.", 6, 100, Color.Black)
            };
            mineralZones = new List<MineralZone>
            {
                new MineralZone(new string[] { "silver_ore_zone" }, "Silver Ore Zone", "A valuable zone for mining silver ore.", minerals[2], 0, 90, 70, 290, 250),
                new MineralZone(new string[] { "platinum_ore_zone" }, "Platinum Ore Zone", "A high-end zone for mining platinum ore.", minerals[7], 0, 0, 0, 280, 70),
                new MineralZone(new string[] { "lapis_lazuli_zone" }, "Lapis Lazuli Zone", "A decorative zone for mining lapis lazuli.", minerals[16], 0, 90, 70, 290, 230),
                new MineralZone(new string[] { "onyx_zone" }, "Onyx Zone", "A powerful zone for mining onyx.", minerals[17], 0, 0, 70, 90, 250),
                new MineralZone(new string[] { "topaz_zone" }, "Topaz Zone", "An enchanting zone for mining topaz.", minerals[18], 0, 0, 250, 150, 370),
                new MineralZone(new string[] { "copper_ore_zone" }, "Copper Ore Zone", "A versatile zone for mining copper ore.", minerals[3], 0, 0, 370, 70, 500),
                new MineralZone(new string[] { "obsidian_zone" }, "Obsidian Zone", "A dangerous zone for mining obsidian.", minerals[4], 0, 70, 370, 170, 650),
                new MineralZone(new string[] { "obsidian_zone" }, "Obsidian Zone", "A dangerous zone for mining obsidian.", minerals[4], 0, 20, 570, 150, 670),
                new MineralZone(new string[] { "obsidian_zone" }, "Obsidian Zone", "A dangerous zone for mining obsidian.", minerals[4], 0, 170, 480, 210, 590),
                new MineralZone(new string[] { "sapphire_zone" }, "Sapphire Zone", "An enchanting zone for mining sapphires.", minerals[12], 0, 0, 0, 0, 0),
                new MineralZone(new string[] { "gold_ore_zone" }, "Gold Ore Zone", "A rich zone for mining gold ore.", minerals[1], 0, 0, 500, 70, 570),
                new MineralZone(new string[] { "gold_ore_zone" }, "Gold Ore Zone", "A rich zone for mining gold ore.", minerals[1], 0, 0, 570, 20, 810),
                new MineralZone(new string[] { "gold_ore_zone" }, "Gold Ore Zone", "A rich zone for mining gold ore.", minerals[1], 0, 20, 670, 150, 710),
                new MineralZone(new string[] { "emerald_zone" }, "Emerald Zone", "An enchanting zone for mining emeralds.", minerals[13], 0, 280, 0, 530, 100),
                new MineralZone(new string[] { "dragonite_zone" }, "Dragonite Zone", "A legendary zone for mining dragonite.", minerals[22], 0, 530, 0, 590, 100),
                new MineralZone(new string[] { "dragonite_zone" }, "Dragonite Zone", "A legendary zone for mining dragonite.", minerals[22], 50, 590, 50, 650, 130),
                new MineralZone(new string[] { "uranium_ore_zone" }, "Uranium Ore Zone", "A powerful zone for mining uranium ore.", minerals[9], 0, 590, 0, 740, 50),
                new MineralZone(new string[] { "uranium_ore_zone" }, "Uranium Ore Zone", "A powerful zone for mining uranium ore.", minerals[9], 0, 650, 50, 710, 100),
                new MineralZone(new string[] { "bloodstone_zone" }, "Bloodstone Zone", "A warrior zone for mining bloodstone.", minerals[27], 0, 740, 0, 800, 50),
                new MineralZone(new string[] { "bloodstone_zone" }, "Bloodstone Zone", "A warrior zone for mining bloodstone.", minerals[27], 0, 710, 50, 830, 100),
                new MineralZone(new string[] { "bloodstone_zone" }, "Bloodstone Zone", "A warrior zone for mining bloodstone.", minerals[27], 0, 700, 100, 890, 210),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 800, 0, 830, 50),
                new MineralZone(new string[] { "titanium_ore_zone" }, "Titanium Ore Zone", "An advanced zone for mining titanium ore.", minerals[8], 0, 830, 0, 960, 100),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 960, 0, 1080, 100),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 890, 100, 990, 200),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 650, 100, 700, 210),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 590, 130, 650, 210),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 590, 210, 880, 240),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 590, 210, 700, 300),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 450, 320, 610, 340),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 550, 250, 610, 320),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 860, 240, 880, 360),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 880, 290, 930, 360),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 770, 360, 870, 400),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 780, 440, 820, 540),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 720, 490, 820, 620),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 450, 340, 500, 420),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 450, 530, 500, 650),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 500, 630, 680, 650),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 610, 590, 720, 620),
                new MineralZone(new string[] { "iron_ore_zone" }, "Iron Ore Zone", "A common zone for mining iron ore.", minerals[0], 0, 610, 620, 680, 630),
                new MineralZone(new string[] { "adamantium_ore_zone" }, "Adamantium Ore Zone", "An indestructible zone for mining adamantium ore.", minerals[6], 0, 990, 100, 1080, 290),
                new MineralZone(new string[] { "adamantium_ore_zone" }, "Adamantium Ore Zone", "An indestructible zone for mining adamantium ore.", minerals[6], 0, 880, 200, 990, 290),
                new MineralZone(new string[] { "opal_zone" }, "Opal Zone", "A mystical zone for mining opals.", minerals[19], 0, 290, 100, 450, 250),
                new MineralZone(new string[] { "pyrite_zone" }, "Pyrite Zone", "A common zone for mining pyrite.", minerals[0], 0, 450, 100, 590, 250),
                new MineralZone(new string[] { "pyrite_zone" }, "Pyrite Zone", "A common zone for mining pyrite.", minerals[0], 0, 450, 250, 550, 320),
                new MineralZone(new string[] { "etherium_zone" }, "Etherium Zone", "A magical zone for mining etherium.", minerals[23], 0, 150, 250, 280, 370),
                new MineralZone(new string[] { "crystal_shard_zone" }, "Crystal Shard Zone", "A magical zone for mining crystal shards.", minerals[29], 0, 170, 370, 340, 440),
                new MineralZone(new string[] { "crystal_shard_zone" }, "Crystal Shard Zone", "A magical zone for mining crystal shards.", minerals[29], 0, 170, 440, 210, 480),
                new MineralZone(new string[] { "indium_zone" }, "Indium Zone", "A rare zone for mining indium.", minerals[36], 0, 280, 250, 450, 370),
                new MineralZone(new string[] { "indium_zone" }, "Indium Zone", "A rare zone for mining indium.", minerals[36], 0, 340, 370, 410, 400),
                new MineralZone(new string[] { "garnet_zone" }, "Garnet Zone", "A powerful zone for mining garnets.", minerals[0], 0, 210, 440, 450, 590),
                new MineralZone(new string[] { "garnet_zone" }, "Garnet Zone", "A powerful zone for mining garnets.", minerals[0], 0, 340, 400, 450, 440),
                new MineralZone(new string[] { "garnet_zone" }, "Garnet Zone", "A powerful zone for mining garnets.", minerals[0], 0, 410, 370, 450, 400),
                new MineralZone(new string[] { "uranium_zone" }, "Uranium Zone", "A radioactive zone for mining uranium.", minerals[65], 0, 700, 240, 860, 360),
                new MineralZone(new string[] { "sunstone_zone" }, "Sunstone Zone", "A luminous zone for mining sunstone.", minerals[26], 0, 610, 300, 700, 360),
                new MineralZone(new string[] { "nickel_zone" }, "Nickel Zone", "An alloy zone for mining nickel.", minerals[33], 0, 500, 340, 610, 630),
                new MineralZone(new string[] { "nickel_zone" }, "Nickel Zone", "An alloy zone for mining nickel.", minerals[33], 0, 450, 420, 500, 530),
                new MineralZone(new string[] { "nickel_zone" }, "Nickel Zone", "An alloy zone for mining nickel.", minerals[33], 0, 610, 360, 720, 590),
                new MineralZone(new string[] { "nickel_zone" }, "Nickel Zone", "An alloy zone for mining nickel.", minerals[33], 0, 710, 360, 780, 490),
                new MineralZone(new string[] { "mythril_ore_zone" }, "Mythril Ore Zone", "A rare zone for mining mythril ore.", minerals[5], 0, 930, 290, 1080, 360),
                new MineralZone(new string[] { "moonstone_zone" }, "Moonstone Zone", "An ethereal zone for mining moonstone.", minerals[25], 0, 870, 360, 1080, 460),
                new MineralZone(new string[] { "cobalt_zone" }, "Cobalt Zone", "A special zone for mining cobalt.", minerals[32], 0, 780, 400, 870, 440),
                new MineralZone(new string[] { "cobalt_zone" }, "Cobalt Zone", "A special zone for mining cobalt.", minerals[32], 0, 820, 440, 870, 500),
                new MineralZone(new string[] { "cobalt_zone" }, "Cobalt Zone", "A special zone for mining cobalt.", minerals[32], 0, 870, 460, 1080, 520),
                new MineralZone(new string[] { "cobalt_zone" }, "Cobalt Zone", "A special zone for mining cobalt.", minerals[32], 0, 1000, 520, 1080, 580),
                new MineralZone(new string[] { "starmetal_zone" }, "Starmetal Zone", "A cosmic zone for mining starmetal.", minerals[24], 50, 820, 500, 870, 580),
                new MineralZone(new string[] { "starmetal_zone" }, "Starmetal Zone", "A cosmic zone for mining starmetal.", minerals[24], 50, 870, 520, 1000, 580),
                new MineralZone(new string[] { "shadow_ore_zone" }, "Shadow Ore Zone", "A stealthy zone for mining shadow ore.", minerals[28], 0, 820, 580, 970, 700),
                new MineralZone(new string[] { "diamond_zone" }, "Diamond Zone", "A hard zone for mining diamonds.", minerals[14], 0, 20, 710, 320, 810),
                new MineralZone(new string[] { "ruby_zone" }, "Ruby Zone", "An enchanting zone for mining rubies.", minerals[11], 0, 970, 580, 1080, 700),
                new MineralZone(new string[] { "ruby_zone" }, "Ruby Zone", "An enchanting zone for mining rubies.", minerals[11], 0, 890, 700, 1080, 810),
                new MineralZone(new string[] { "amethyst_zone" }, "Amethyst Zone", "A magical zone for mining amethysts.", minerals[15], 0, 170, 590, 450, 650),
                new MineralZone(new string[] { "zircon_zone" }, "Zircon Zone", "A durable zone for mining zircons.", minerals[21], 0, 150, 650, 380, 710),
                new MineralZone(new string[] { "seaborgium_zone" }, "Seaborgium Zone", "A radioactive zone for mining seaborgium.", minerals[79], 0, 320, 710, 810, 810),
                new MineralZone(new string[] { "bismuth_zone" }, "Bismuth Zone", "An alloy zone for mining bismuth.", minerals[31], 0, 810, 700, 890, 810),
                new MineralZone(new string[] { "yttrium_zone" }, "Yttrium Zone", "A phosphorescent zone for mining yttrium.", minerals[45], 0, 680, 620, 820, 710),
                new MineralZone(new string[] { "lutetium_zone" }, "Lutetium Zone", "A heavy zone for mining lutetium.", minerals[60], 0, 380, 650, 680, 710),
            };
        }
        public MineralType AssignMineral(double x, double y)
        {
            foreach(var zone  in mineralZones)
            {
                if(IsInZone(x, y, zone))
                    return zone._mineral;
            }
            return null;
        }
        private bool IsInZone(double x, double y, MineralZone zone)
        {
            return (x > zone.startX && y > zone.startY && x < zone.endX && y < zone.endY);
        }
    }
}
